[tool.poetry]
name = "whisper-streaming"
version = "0.1.0"
description = ""
authors = ["Yuta Hayashibe <yuta@hayashibe.jp>"]
readme = "README.md"
packages = [{include = "whisper_streaming"}]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
whisper = {git = "https://github.com/openai/whisper.git", rev = '15ab54826343c27cfaf44ce31e9c8fb63d0aa775'}
sounddevice = "^0.4.5"
pydantic = "^1.10.2"


[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
isort = "^5.10.1"
flake8 = "^5.0.4"
pydocstyle = "^6.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
whisper_streaming = "whisper_streaming.cli:main"

